annotations:
  category: MachineLearning
  licenses: Apache-2.0
apiVersion: v2
appVersion: "1.17.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.26.0
  - name: keycloak
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
    version: 24.0.1
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: authhelper
    condition: authhelper.enabled
    version: 2.0.0
  - name: dial-core
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: core
    condition: core.enabled
    version: 4.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: chat
    condition: chat.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: themes
    condition: themes.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: openai
    condition: openai.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: bedrock
    condition: bedrock.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: vertexai
    condition: vertexai.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: assistant
    condition: assistant.enabled
    version: 2.0.0
  - name: dial-extension
    repository: https://nepalevov.github.io/ai-dial-helm
    alias: dial
    condition: dial.enabled
    version: 2.0.0
description: Umbrella chart for DIAL solution
home: https://epam-rail.com
icon: "https://docs.epam-rail.com/img/favicon.ico"
keywords:
  - ai-dial
kubeVersion: ">=1.23.0-0"
maintainers:
  - name: EPAM Systems
    url: https://github.com/epam
name: dial
sources:
  - https://github.com/epam/ai-dial-helm/tree/main/charts/dial
version: 4.0.0
